platform: linux
image_resource:
  type: docker-image
  source:
    insecure_registries: ["10.234.24.211:443"]
    repository: 10.234.24.211:443/debian
    tag: latest
inputs:
- name: gitfolder 
- name: bin
outputs:
- name: peppermint-sparkles
run:
  path: sh
  args:
  - -exec
  - |
    set -o errexit
    set -o xtrace

    # TARGET="peppermint-sparkles"

    # ensure 'peppermint-sparkles/build/bin' directory exists
    # mkdir -p ${TARGET}/build/bin

    # merge source and binary into expected repo dir 'peppermint-sparkles'
    # mv source/* ${TARGET}/ && \
    # mv gitfolder/* ${TARGET}/ && \
    #   mv bin/* ${TARGET}/build/bin/

    mkdir -p gitfolder/build/bin && \
      cp -rf bin/* gitfolder/build/bin/